[Settings]

# 使用自己的频道模板，决定频道分类和排列顺序
source_file = config/user_demo.txt

# 使用自己的结果文件
final_file = output/user_result.txt

# 调试阶段保留无结果频道，方便发现缺源频道
open_empty_category = True

# 不输出模板之外的频道
open_unmatch_category = False
